### ISSUE TITLE
Send Jenkins URL to dashboard

### ISSUE THREAD

**Issue by davehunt** [mozilla/mozmill-ci#189]
It would be great if we could show the Jenkins URL in the dasboard. Part of this would involve sending the URL from the job, probably as a testrun description. This is currently blocked by https://github.com/mozilla/mozmill-dashboard/issues/18

**Comment by whimboo** [comment]
We don't have the dashboard anymore, but with firefox-ui-tests the build url is part of the uploaded artifacts:

https://treeherder.mozilla.org/logviewer.html#?job_id=2166519&repo=mozilla-central

So I call this fixed. :)
