### ISSUE TITLE
Update virtualenv to latest version

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#207]
Our virtualenv version is kinda outdated. It should be updated to the latest release. We might also have to check which options have been changed for creating the env.

**Comment by simar7** [comment]
Is this still an outstanding issue to work on?

**Comment by whimboo** [comment]
@simar7 this is indeed an open issue. It hasn't visited for a while so a more recent version of virtualenv will be available. We would have to check if that version works correctly. Would you be interested in to work on this?

**Comment by simar7** [comment]
@whimboo Yes, I'm interested!

**Comment by simar7** [comment]
New virtualenv revisions can be found here: http://virtualenv.readthedocs.org/en/latest/changes.html

**Comment by simar7** [comment]
Initial change, ran setup.sh and seem to setup fine: https://github.com/mozilla/mozmill-ci/pull/549

Anyone have any ideas on how I should test this? I was thinking of running run_tests.sh to start of with.

**Comment by whimboo** [comment]
PR #549 upgraded virtualenv to version 12.0.6.
