### ISSUE TITLE
Compress build artifacts to conserve disk space

### ISSUE THREAD

**Issue by davehunt** [mozilla/mozmill-ci#306]
We have recently added HTTP logs and screenshots as build artifacts. The log files can be > 6MB and are stored uncompressed. We should investigate adding compression to these artifacts.

I found [JENKINS-6229](https://issues.jenkins-ci.org/browse/JENKINS-6229) which suggests a plugin will be released soon that offers compressing artifacts.

**Comment by whimboo** [comment]
Artifacts are already uploaded to S3 for firefox-ui-tests. I don't think there is anything we wanna do for the remaining ondemand update tests which get still run with Mozmill. So closing issue.
