### ISSUE TITLE
master shutdown due to no memory available

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#314]
Not sure what exactly happened here but our master shutdown due to memory problems:

 A fatal error has been detected by the Java Runtime Environment:

  Internal Error (instanceKlass.cpp:1534), pid=3617, tid=239283008
  Error: ShouldNotReachHere()

 JRE version: Java(TM) SE Runtime Environment (7.0_40-b43) (build 1.7.0_40-b43)
 Java VM: Java HotSpot(TM) Client VM (24.0-b56 mixed mode linux-x86 )
 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /data/mozmill-ci/hs_err_pid3617.log

 If you would like to submit a bug report, please visit:
   http://bugreport.sun.com/bugreport/crash.jsp

./start.sh: line 25:  3617 Aborted                 (core dumped) java -jar -Xms2g -Xmx2g -XX:MaxPermSize=512M -Xincgc $JENKINS_WAR

**Comment by indrayam** [comment]
We came across this error in our Jenkins instance. We were on 1.565 at the time using Java 1.7. We have upgraded since then. However, just curious. Do you know what might have solved your problem? Also, I notice that you set the -Xms and -Xmx to the same value? Is that by design?

**Comment by whimboo** [comment]
We never figured out the real problem for that shutdown. But that was not necessary given that we never trapped into it again after I did the upgrades. Regarding the memory options we put them in a long time ago. I cannot tell out of my head why those have the same number.

**Comment by dalvizu** [comment]
> Regarding the memory options we put them in a long time ago. I cannot tell out of my head why those have the same number.

This is a common practice to prevent the jvm heap from resizing itself as a performance tweak.
