### ISSUE TITLE
start a virtualenv for pulse.py at the beginning of the script using activate_this.py

### ISSUE THREAD

**Issue by Nebelhom** [mozilla/mozmill-ci#343]
So far, we need to manually start the virtual environment from the command line before starting pulse.py

It is possible to create a virtualenv from inside the script using `activate_this.py`, so I think we should use it.

Compare:

http://www.virtualenv.org/en/latest/#using-virtualenv-without-bin-python
http://stackoverflow.com/questions/6943208/activate-a-virtualenv-with-a-python-script/14792407#14792407

**Comment by whimboo** [comment]
PR #682 has been merged to master.

**Comment by whimboo** [comment]
I have updated the wiki (https://github.com/mozilla/mozmill-ci/wiki/Running) to reflect those changes.
