### ISSUE TITLE
Check Mozmill Automation how Mercurial returns the exit code for all platforms in case 'hg pull' fails

### ISSUE THREAD

**Issue by andreieftimie** [mozilla/mozmill-ci#408]
See issue #356 for more details.

This has been fixed for now, but we should investigate further if any other failures might happen. 

Steps. should be to undo the fix from #356 and run on a local mozmill-ci instance to reproduce the error (intermittent) and see if it fails in any other way.

**Comment by whimboo** [comment]
Mozmill is plainly dead. WE only need this for ondemand update tests. I don't think that we should put any afforts into this issue.
