### ISSUE TITLE
Jobs running much longer than expected

### ISSUE THREAD

**Issue by davehunt** [mozilla/mozmill-ci#420]
I noticed on 24th February 2014 that get_mozmill-tests was taking a long time (at the time I looked it was around 30 minutes, and it's usually at most two minutes). It then became obvious that it was not the only job, and several had stalled.

It turned out that many threads were blocked, apparently by the ConsoleHandler. I was about to try a Jenkins restart when I noticed that we are still having a number of exceptions due to "Failed to rotate log", and just as I was looking into details of this exception, the stalled builds completed. I can't say if it was related to my actions, or if it was something else.

I did find [JENKINS-19377](https://issues.jenkins-ci.org/browse/JENKINS-19377) which indicates that maybe this exception we're seeing will be fixed in a later Jenkins release, but I'm not entirely sure if it's even related to the strange stalled jobs we saw.

**Comment by whimboo** [comment]
We haven't seen that again or it was not that obvious. But given that Mozmill CI will be killed in the next couple of months, it's not something we want to fix.
