### ISSUE TITLE
Run jenkins (and maybe the pulse listeners) as a daemon and tail their log into screen

### ISSUE THREAD

**Issue by andreieftimie** [mozilla/mozmill-ci#444]
We've recently had 2 instances of Jenkins becoming non-responsive and builds queuing up being unable to finish.

The reason was that screen was set into scroll/copy mode and that blocked the jenkins process.

One possible solution would be to stop running these scripts from within screen. Start them up as a daemon and tail the log output into the screen tab. This should provide greater resilience.

**Comment by whimboo** [comment]
We kill the project in the next couple of months in favor of TaskCluster. So it's nothing we want to get implemented.
