### ISSUE TITLE
Rename OSX 10.7 machines to OSX 10.10

### ISSUE THREAD

**Issue by andreeamatei** [mozilla/mozmill-ci#479]
As decided, we want to change the 10.7 machines to the new release 10.10, so we'll need to rename them on the CI.

**Comment by whimboo** [comment]
PR #582 for production machines has been merged. I will push this to production soon.

**Comment by whimboo** [comment]
The first two 10.10 nodes have been enabled on production. I requested the re-provisioning of the other two.

**Comment by whimboo** [comment]
All nodes have been upgraded from 10.7 to 10.10 and are available now in the production environment.
