### ISSUE TITLE
Send email notifications via pulse.py when a build is marked as broken

### ISSUE THREAD

**Issue by andreeamatei** [mozilla/mozmill-ci#482]
Like i said in issue #481 , when we deal with broken builds (non zero status), we also want to get notification via email. Right now, when we see broken builds is when we do the testrun reports and notice some haven't run. Then we manually investigate, check the logs.

**Comment by simar7** [comment]
Is this still an outstanding issue to work on? Sounds like a neat idea to have!

**Comment by whimboo** [comment]
@simar7 this is indeed an outstanding feature to be implemented. Sadly we haven't had the time for that yet. Would you be interested in working on it? I'm happy to mentor you through the whole process.

**Comment by simar7** [comment]
@whimboo Absolutely! Would you be interested in discussing this further on IRC? My nick is simar|on and I usually lurk around on #ateam and #releng

**Comment by whimboo** [comment]
I would suggest to let us fix issue #207 first, before you get to this issue.

**Comment by whimboo** [comment]
@simar7 are you still interested to work on this bug? Keep in mind that it will be a more challenging one. But if you don't mind I'm happy to mentor you through the process.

**Comment by simar7** [comment]
@whimboo I'd love to but currently working on a few other bugs that are taking up my time. I'd finish them first (so I don't leave them halfway through) then if this is still up for grabs, I'd be happy to help.

**Comment by whimboo** [comment]
Good to hear. So let us know when you are available again. I will not assign the issue to you since then. Thanks.

**Comment by ibrahimsharaf** [comment]
Hello @whimboo, I want to work on this issue, how can I begin?

**Comment by whimboo** [comment]
Hi @ibrahimsharaf. Thank you for your interest in working on this issue. In the last year we have an ongoing activity to actually get rid of a lot of code of mozmill-ci, which also included Jenkins. It means that we might want to wait with any kind of work on this issue until the big refactoring has been done. Also as all the last months have been shown, it's not really a critical piece anymore in our infrastructure.

So if you are interested in something else, I'm happy to mentor issues for https://github.com/mozilla/mozdownload, or Marionette (https://wiki.mozilla.org/User:Mjzffr/New_Contributors). Just let me know. Thanks.
