### ISSUE TITLE
Investigate a way to take a node offline without disruption

### ISSUE THREAD

**Issue by andreieftimie** [mozilla/mozmill-ci#503]
As we've recently seen we really need a way to properly take a node offline without disrupting the currently running builds.

I've found a Jenkins plugin that claims to solve this issue:
https://wiki.jenkins-ci.org/display/JENKINS/Lenient+shutdown+plugin

(Maybe there are other alternatives, this needs to be investigated and tested)

We need a way to take a node offline _after_ the currently running build is finished.

**Comment by amansukhaniEBSCO** [comment]
Is there a way to find out when all the builds on an offline are finished, and delete that node automatically? I have seen a configuration in the Jenkins Node Part that says offline a node when there is 1GB of free space left, but it does not delete the node after all the builds on it are finished. 

Is there a job I can run to do this? or a Groovy DSL script?

**Comment by whimboo** [comment]
There is nothing we can help you with. Please consult the appropriate support site for the Jenkins plugin or some support channel. This is just a repository which uses Jenkins.
