### ISSUE TITLE
Stop sending emails to mozmill-ci mailing list for test failures only

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#550]
The amount of emails we get to our mozmill-ci mailing list is overwhelming. We should drastically reduce it to an amount we can handle by one person. One thing we should do is to simply stop sending emails in case of test failures. Given that we have our dashboard, that one has to be used for observing such problems.

The only emails we should send to the mozmill-ci list are for disconnects or aborts of test runs, and node offline messages.

**Comment by whimboo** [comment]
To archive that we might have to update the XShell command and evaluate the return code from the automation scripts. In case of test failures we return with an exit code of 2.

@davehunt, do you have any idea how we can mark the the build as failed but not sending out an email based on this exit code? I assume Jenkins marks the result based on the exit codes of the commands, or does it also work for the result coming out of the junit report?

**Comment by davehunt** [comment]
As mentioned on IRC I believe the unstable trigger is used in the case where the shell exits normally but the JUnit report contains failure. If you catch exit code 2 and rethrow exit code 0 then you can either remove the unstable trigger or easily filter these out.

**Comment by whimboo** [comment]
There are some problems here. So we do not have an unique exit code for test failures. I have seen this right now when playing with the testrun scripts and not specifying a binary. Looks like we pass-through the exit code from mozmill, which is 2 in this case.

There are also problems with XShell which doesn't let me `||` in the shell code. It interprets all as a single command. So a fix for that would be way more complex and I don't think its worth of my time here.

We could re-evaluate if it becomes important again but if tests are starting to fail we mostly want to skip them until  they are converted to a Marionette test. cc'ing @AutomatedTester for info.
