### ISSUE TITLE
If a node has low disk space it should be marked offline automatically

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#555]
See [bug 1134117](https://bugzilla.mozilla.org/show_bug.cgi?id=1134117) as reference. We had an abnormal working machine and it was not taken offline automatically. As result we got hundreds of failing tests. :(

I cannot find a built-in feature to do that. But I think there has to be a plugin. @davehunt do you have any experience?

**Comment by davehunt** [comment]
Jenkins should take a node offline if the disk space falls below a certain threshold. This can be configured here: http://mm-ci-master.qa.scl3.mozilla.com:8080/computer/configure

**Comment by whimboo** [comment]
@davehunt that's exactly what we did. There is a threshold of 1GB entered. So having only 14MB left on a node's disk should have it made offline. I would assume it's a bug in Jenkins then.

**Comment by davehunt** [comment]
That sounds likely. Did the free space decrease from > 1GB to ~14MB rapidly? It could be that the space was consumed faster than the polling of the Jenkins check. If so, we might want to increase the threshold.

**Comment by whimboo** [comment]
The problem here were the full minidump files we have created for crashes on this host. Each of those are 300MB in size! So seeing 3 crashes in a single testrun and the remaining disk space was full. @davehunt do you know how often Jenkins checks for the free disk space?

**Comment by davehunt** [comment]
Not without digging, no.
