### ISSUE TITLE
Stop running addon tests

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#560]
We do not have the time anymore to watch test results for add-on tests. Given that we only have a single add-on covered so far, we want to shut off testing in our CI. @davehunt do you have any objections?

**Comment by davehunt** [comment]
No objections, especially as the one addon we test is currently not actively maintained and likely to suffer issues with e10s.

**Comment by whimboo** [comment]
Sounds good then! I will work on a patch tomorrow to get addon tests disabled. cc'ing @AutomatedTester.

**Comment by whimboo** [comment]
PR #565 has been merged.
