### ISSUE TITLE
Enable Firefox win64 builds for beta and release in Mozmill CI

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#566]
We already enabled Firefox 64bit builds for Nightly and Aurora in issue #548, but we also have to do this now for beta and release.

**Comment by whimboo** [comment]
PR #567 has been merged. I will push it to staging first for the next beta. If all works well we can then also enable it for production.

@kairo-at is that ok for you? I wanna do it this way to minimize the amount of failures we may get on production.

**Comment by KaiRo-at** [comment]
This is fine as long as we don't see too many failures. Win64 will NOT be shipped to users for Firefox 37 (i.e. current Beta), we only have Win64 enabled on beta now to find issues already before the 38 train hits, as that one is the current target to ship Win64.

**Comment by whimboo** [comment]
Ok, so if something still needs fixes we have a bit of time.

**Comment by whimboo** [comment]
Tests on staging look great for Firefox64 builds. I'm going to push this to production now, and restart the release listener.

**Comment by whimboo** [comment]
This is now alive on production. For the next beta build we will have win64 coverage! cc'ing @ctalbert for information.
