### ISSUE TITLE
Stop running tests for zh-CN locale for Aurora because loading the default homepage times out

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#571]
As we have seen in [bug 1142922](https://bugzilla.mozilla.org/show_bug.cgi?id=1142922) we have lots of page load timeouts lately with the zh-CN locale. We should stop running tests for it until it has been fixed. As alternative we have zh-TW which is not using a custom default homepage via mozillaonline.

**Comment by whimboo** [comment]
CC'ing @kairo-AT for info.

**Comment by whimboo** [comment]
@pike had concerns on IRC to disable beta and release testing. @kairo-AT would you have any problem with seeing those test results on and off in the release test results?

**Comment by KaiRo-at** [comment]
I guess using China's Internet from our side can be hard to access at times. I'm not feeling too good with disabling. zh-TW and zh-CN are two completely independent localizations, they just happen to be variants of the same base language - but zh-CN is used by *way* more people.

**Comment by whimboo** [comment]
Ok, so I would suggest we do the following: For aurora we test zh-TW so we have a proper UTF8 locale in our test matrix. And for beta and release I will not blacklist zh-CN and you will have to live with the failures. Is that ok for you?

**Comment by KaiRo-at** [comment]
Fine with me, for now.

**Comment by whimboo** [comment]
PR #572 has been merged. I will rebase all the latest changes to staging and production once Travis gives us a complete pass.
