### ISSUE TITLE
Add jobs for Firefox 38.0 ESR release

### ISSUE THREAD

**Issue by otiliaanica** [mozilla/mozmill-ci#577]
With the upcoming Firefox 38.0 release we will have our next ESR release. That means we will have to handle both the ESR31 and ESR38 release. ESR31 will be stopped supporting in about 2 months.

@whimboo can you please help with creating these new jobs? Thanks!

**Comment by whimboo** [comment]
I totally missed this part the last days. Thanks for letting me know and sorry for the delay. At least for update tests you are not blocked, and that is the important fact. I will get this implemented today.

**Comment by whimboo** [comment]
PR #578 has been merged. I already pushed the changes to staging. It looks fine but I would like to wait at least until tomorrow before I will update production too.

**Comment by whimboo** [comment]
Ok, everything is in production now too. You are good to get some of the tests triggered manually.

**Comment by otiliaanica** [comment]
Thanks Henrik!
