### ISSUE TITLE
Implement report submission to treeherder for firefox-ui-tests

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#595]
This is a spun-off issue beside the tracking [bug 1166683](https://bugzilla.mozilla.org/show_bug.cgi?id=1166683). It's simply about the plain implementation of the feature.

I'm currently working on it and have already the basics implemented. Maybe by end of this week I will have the PR up.

**Comment by whimboo** [comment]
I will do this issue in two stages. First I will enable  the daily builds to report to treeherder. Then if all is goin well, I will also enable release jobs to report to it. I will wait with the PR until #596 has been landed.

**Comment by whimboo** [comment]
I have problems right now to pass over the environment variables from the master to the slaves. Whenever those are set via a properties file on the master, I do not see them on the slave, even not when specifying to pick the properties file from the master. I will have to dig into this more tomorrow.

@davehunt do you have a hint how to securely pass over credentials for treeherder from the master to the slaves? I don't to make those parameters for the jobs.

**Comment by davehunt** [comment]
With EnvInject you can specify passwords in the global configuration, which are injected at the start of each build regardless of the slave that's running the job.

**Comment by whimboo** [comment]
This won't work given that those entries have to be entered as name/value entries in the Jenkins configuration. The way how we handle the configs would overwrite it each time we push updates to production. :( A reference to a password file might have worked. So I will continue to check if I can get it working or if there is a plugin we could make use of and which is compatible with our LTS version. I really don't want to upgrade Jenkins now when I head out for a month.

**Comment by whimboo** [comment]
So the described behavior should indeed be a bug in the envinject plugin. I filed it as https://issues.jenkins-ci.org/browse/JENKINS-29056. For the time being it will work to load this properties file in each job which has to make use of treeherder. I think that this is totally ok for now.

**Comment by whimboo** [comment]
The last bits have been landed on master. I'm going to merge and push to staging and production. There is minimal risk in breaking something.

**Comment by whimboo** [comment]
It's all live now! Yay! Nothing more to do here. Given that staging and production would report both to treeherder staging I will stop submitting test results for staging by removing the env variables for AWS and Treeherder in .jenkins.properties

**Comment by whimboo** [comment]
For release builds I missed to stop sending out emails for unstable builds. I will come up with a PR soon.

**Comment by whimboo** [comment]
PR #607 got landed and I will merge it soon to staging and production.
