### ISSUE TITLE
Remove Ubuntu 14.10 machines

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#603]
Similar to Windows we want to limit ourselves to only those platforms which are really important. Given that we have also 14.04 which is the LTS release of Ubuntu, we only want to keep this version. The normal Ubuntu release will be removed from our testing matrix.

CC'ing @kairo-at and @ashughes1 for information.

**Comment by whimboo** [comment]
PR #603 has been merged and will be pushed out together with the treeherder changes.

@kairo-at please do no longer use Ubuntu 14.10 in your update test config files. Thanks.

**Comment by KaiRo-at** [comment]
I just realized this means we are only testing with one Linux version at all now, which concerns me quite a bit, esp. as it is a much older version of libraries than most of our Linux users will run (but then, most of those do not run out binaries but distro-provided ones).

**Comment by whimboo** [comment]
This is what we even do on buildbot, except that we have 14.04 but buildbot only 12.04. We have to limit the number of machines to adjust the maintenance to the fact that only myself is managing this cluster and we want to go to buildbot / task cluster anyway. If there is no support for a newer release, we cannot cover it. If you have concerns with that feel free to get in contact with @AutomatedTester.
