### ISSUE TITLE
Ensure to mark the build as failed if final report submission to treeherder fails

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#608]
I have seen that we are failing to submit results to treeherder. The reason is an API change and that the new treeherder client version was not mirrored to the internal PyPI mirror. Sadly we have not seen that because no failure email has been sent out.

So as I talked with @edmorley on IRC it would be good to at least remove the try/except from the final report submission. That way we can mark the build as failed, but can still run all of our tests and get results. Downside would be if the treeherder server is not reachable due to network issues we will get failing tests, but I hope that this will not happen that often. :)

**Comment by edmorley** [comment]
> Downside would be if the treeherder server is not reachable due to network issues we will get failing tests, but I hope that this will not happen that often. :)

Ideally submission should be retrying and/or looking at the HTTP code returned from Treeherder's API (ie in this case you would presumably have received 404s, which shouldn't retry and should fail more noisily). Perhaps this is something we should add in the client?

**Comment by whimboo** [comment]
Yeah. I think having the retry logic in treeherder-client for failures which could be solved with a retry, that would be great. That way we would know if the call raises we have a real failure.

**Comment by whimboo** [comment]
PR #609 has been merged. I will merge to staging and production once the treeherder-client 1.6 has been mirrored to the internal pypi.
