### ISSUE TITLE
Improve funsize updates handling via taskcluster 

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#627]
Right now we are only listening for the funsize-balrog worker task to be ended, and always fetch the manifest file with the update information. This happens regardless if it is one of the wanted locales, platforms, or branches. This is inefficient because a request for the manifest has to be made against taskcluster, and the manifest has to be downloaded. This causes extra resources and time.

I chatted with @rail and @petemoore on IRC and we found the following solutions:

* Each pulse notification from taskcluster has custom routing keys assigned to it. Thing is that those are not part of the body but the message header. I just checked that and we get e.g.  `route.index.funsize.v1.mozilla-aurora.latest.win32.pl.3.balrog`. With that we can run a regex on the routing_key to directly dismiss unwanted messages.

* Further the second last part (in the above example `3`) contains the actual partial update time range which is `today - 3`. All in all we have 1 to 4 here, which I highly want to use on treeherder to better identify the different update tests. Right now we have: `Fu( en-US en-US en-US en-US)`. With the change we will get `Fu( en-US-1 en-US-2 en-US-3 en-US-4)`.

* Beside that we could also limit the amount of updates we actually want to test in the future. If we e.g. want to only test the latest partial for localized builds, we could dismiss any message except `1`.

**Comment by whimboo** [comment]
As seen on [bug 1189267](https://bugzilla.mozilla.org/show_bug.cgi?id=1189267) there is a limitation of 10 routing keys. This would not work so an idea is to list all included locales separated with underscores in the same routing key:

`index.funsize.v1.mozilla-aurora.latest.linux64.be_bg_bn-BD_ast_bn-IN.1.updates`

@rail, I will adjust my code to use this option for now.

**Comment by petemoore** [comment]
@whimboo just be aware that routing keys are limited to 255 bytes, so assuming only ascii chars, that would also be 255 chars. I'm not sure how many locales could appear in the routing key, just wanted to highlight this limitation early. =)

**Comment by whimboo** [comment]
PR #630 got merged. Now the handling of the update number is left to do.

**Comment by whimboo** [comment]
Ok, so the idea of having routing keys for different locales in funsize notifications doesn't scale. After talking to jonasfj we are going back to the beginning. It means no pre-processing of the funsize notifications but always downloading the manifest. It's not a win, but every other option has limitations.

I will implement the appropriate code for us once those pieces have been landed.

**Comment by whimboo** [comment]
The patch for handling multiple locales inside the manifest file has now been landed via PR #634. So only the update number PR is missing now.

**Comment by whimboo** [comment]
PR #636 for the update numbers has been merged. So all is done here. I will push all the changes to staging in a bit so we can let it bake over the weekend. Thank you all for your assistance!
