### ISSUE TITLE
Exchange custom run_tests scripts with mozharness

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#642]
To finish [bug 1192369](https://bugzilla.mozilla.org/show_bug.cgi?id=1192369) we have to replace the custom runner scripts under the scripts job with mozharness.

**Comment by whimboo** [comment]
Current work for the CI configuration can be seen on my mozharness branch:
https://github.com/mozilla/mozmill-ci/compare/master...whimboo:mozharness

**Comment by whimboo** [comment]
Talking to @sydvicious and @mjzffr today I got the info that it might be very helpful for Syd to already have the get_mozharness job present. So I will go and strip those commits of my mozharness branch to have a PR ready later today.

**Comment by whimboo** [comment]
PR #684 got landed. With it the clone workspace step can be used to get a copy of mozharness on the slaves.

**Comment by whimboo** [comment]
@mjzffr and @sydvicious would the media test jobs in Jenkins need the Git plugin? I doubt so and I would like to remove it from mozmill-ci. If mozharness needs git it can be used via `external_tools/gittool.py`.

**Comment by sydvicious** [comment]
Well, something has to get firefox-media-tests.git until it is put into mozilla-central. Could we wait to remove it until that happens?

**Comment by whimboo** [comment]
It would be better if we have a mozharness step which gets the tests similar to firefox-ui-tests. This would only be called in case of Jenkins but not buildbot.

**Comment by mjzffr** [comment]
If we want a 'checkout' step in mozharness anyway, I recommend to replace
run_media_tests.py by resolving
https://bugzilla.mozilla.org/show_bug.cgi?id=1210486 first, since a
suitable checkout step is already implemented in firefox_media_tests.py in
m-c.

Maja Frydrychowicz
irc: maja_zf

**Comment by whimboo** [comment]
That sounds like the correct approach to me.

**Comment by whimboo** [comment]
PR #698 got merged to master. I will push to staging immediately. Production might follow next once we are confident all works and smaller bugs have been fixed.
