### ISSUE TITLE
Staging should only run a limited number of partial update jobs

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#646]
As of now we run all partial updates (-1, -2, -3, and -4). To verify that partials are working, I would suggest we limit the number of update tests run to only 2 at maximum.

**Comment by whimboo** [comment]
@rail I think that I would like to see that we run 1 partial update for each covered locale in our staging environment so we can check that it works. Which one would be best? Personally I would pick -1, so the most recent one.

**Comment by rail** [comment]
yeah, -1 is the most important.
