### ISSUE TITLE
Implement postbuild actions to upload artifacts to S3 and submit reports to Treeherder

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#661]
As discussed on [bug 1207581](https://bugzilla.mozilla.org/show_bug.cgi?id=1207581) and [bug 1207580](https://bugzilla.mozilla.org/show_bug.cgi?id=1207580) we cannot include the code for uploading artifacts to S3 and submitting to treeherder in the mozharness script. It has not been built for it. Instead the consumers of mozharness will have to ensure to do those task themselves.

Given that we want to utilize Taskcluster (http://docs.taskcluster.net/) in the near future to run some of our tests (Linux works so far, OS X support to come in Q1, Windows support to come in Q2) beside our usual Jenkins jobs we have to find a way to cover both worlds. In the following some ideas:

1. We keep the Pulse listener script as it is and once we add support for TC we update its code to not push to Jenkins but to TC. Given that TC handles upload to S3 and treeherder submission itself, we can limit our custom S3 and Treeherder code to Jenkins. Maybe best as a postbuild action which gets also run in case of an abort of the build. We have to determine options which works best for us given that there are couple of plugins out there like [PostBuildScript](https://wiki.jenkins-ci.org/display/JENKINS/PostBuildScript+Plugin), [PostBuildTask](https://wiki.jenkins-ci.org/display/JENKINS/Post+build+task), or the more advanced [WorkFlow](https://github.com/jenkinsci/workflow-plugin) plugin.

2. We improve the pulse listener and add a scheduling mechanism to it, which triggers builds for Jenkins or TC and keeps the Jenkins builds in a queue as long as they are not finished. Once done it will send the results to treeherder. Keep in mind that we won't be able to submit a result to treeherder that the tests have been started. With it we most likely have to pull each of the Jenkins jobs in the queue for completeness. I haven't seen push notifications yet for the Jenkins API. So this might cause a higher cpu load in case of at least releases. At least we can ensure to not throw away pulse notifications in case Jenkins is down. 

Personally I would favor 1) because it seems to be lesser work involved here. Especially that we might only need Jenkins for the next year or so. Also the e.g. workflow plugin gives us a fantastic amount of new features which will also make the maintenance of jobs and the running instances easier. This plugin might not be on my list for now given that it is complex to integrate, but it's something we should think about for the future.

Today I will try out the post build plugins to see if aborting builds will correctly run our upload and reporting code.

CC'ing @AutomatedTester, @mjzffr, and @sydvicious for information.

**Comment by sydvicious** [comment]
I think that this should be per-job, and the job should know whether it is running on Jenkins or in taskcluster. Trying to keep a set of projects that depend on each other in Jenkins in sync is a pain. It can be done, but keeping it in the job will be easier.

**Comment by whimboo** [comment]
The changes as described here are only for Jenkins. Taskcluster has its own code to submit results to Treeherder and we will never touch that. The only thing we will have to do in such a case is to set the correct group and job names and symbols.

So the postbuild action is listed above is configurable per job. If you don't want that you don't have to use it. But keep in mind that in case of aborts no `completed` state will be pushed to Treeherder and your job will still be marked as `running`.

As mentioned in our meeting my PR for this issue should be up by today.

**Comment by whimboo** [comment]
So I got it nearly finished but stumbled a bit with the remaining bits specifically to have it correct for using it with mozharness and the combination of Jenkins/Buildbot/Taskcluster. Because of that I had a chat with Maja yesterday especially about the media tests. As she told me nothing in the tests actually assembles the failures, uploads files to S3, nor submits results to treeherder. All is done magically via buildbot based on the return value of the script and the created log files.

That means in Jenkins we also have to allow that magic. Best would be to have a single wrapper script which sends the `running` report, executes the tests, and sends the `completed` reports. Sadly this is not working due to the known problems with aborted builds. I tested it again on a Linux slave with signal handlers in place for SIGINT and SIGTERM. Both do NOT fire in case of an abort, so it looks like the job gets hard killed. The only way which remains here is to execute postbuild actions including the sending of the `completed` result. Therefore the postbuild plugin can be used as already mentioned above.

Given that the submission to Treeherder will need the treeherder-client package to be installed on the slaves and I don't want to make this globally, a virtual environment has to be created. But I don't want to keep this active for running the tests because mozharness will create its own virtual environment with all the Marionette packages. I feel its better to keep both virtualenvs separated. The benefit for Treeherder submission would be that the creation of the venv will be much faster and less error prone which is important that we definitely can submit both reports. Maybe best would be to do the submission via the master to save the time to create the venv but I cannot find a way to do so. Eventually the workflow plugin could help but it's definitely nothing for now.

So here how it will work for us:

1. A submission.py script will handle the report submission to Treeherder and the upload to S3. It will detect if the required virtualenv exists, and if not it will create it. The report will be sent and the used job guid is saved to a file for later usage.

2. A runtests.py wrapper script will execute the real tests (which will later be the mozharness script) by simply passing through all arguments. In the case of our current runtests.py script we will create our env on our own. Full logs will be written out to the log folder and the return code is also written to a file.

3. In the postbuild step the submission script is run again. It reads in both the job guid and the return value, runs the output parser over the all-in-one log file, uploads all requested files, and sends the report to Treeherder.

In case of an abort during step 1 we can not ensure that anything gets send to Treeherder, here the postbuild step has to take it into account. In case of step 2 the script will be aborted and most likely no return value written to the file. I might treat this as unknown result.

**Comment by whimboo** [comment]
Given that we will need virtualenv installed once we run mozharness and I want to also make use of it for the Treeherder virtual env I filed [bug 1212922](https://bugzilla.mozilla.org/show_bug.cgi?id=1212922) to get our slaves updated.

**Comment by whimboo** [comment]
I'm going to not install virtualenv on each slave. It's way too time consuming. Instead we will distribute it via the scripts job in Jenkins. The scripts are working now. What's remaining is the update of all the job configs and some clean-up. So the PR will be up tomorrow.

**Comment by davehunt** [comment]
You might want to check out the [Custom Tools Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Custom+Tools+Plugin), which can be configured to install tools to the slaves.

**Comment by whimboo** [comment]
Would be an idea. How does it work for different platforms? Also will it check if the tool is already installed, or will it install it over an installed version anyway? I would like to limit the access to any remote site and better stick virtualenv completely in the script job workspace.

**Comment by davehunt** [comment]
> How does it work for different platforms?

I believe it matches the labels, but I was forgetting that you need to support Windows. I'm not sure it would be that easy to use with that platform.

**Comment by whimboo** [comment]
Yes, that is what I'm thinking. I will keep the virtualenv distribution in the scripts jobs, and create a new matrix job which generates the treeherder venv for us. That way the slaves won't have to create it each time and we can directly send the `running` state to treeherder and won't fail due to a non-existent environment in case of an abort.

**Comment by whimboo** [comment]
So matrix job will not be possible because the virtualenv would not be relocatable to other jobs.

**Comment by whimboo** [comment]
PR #671 got merged to master. I will push those changes to staging in a bit. Maybe later this week we can even deploy to production.

**Comment by whimboo** [comment]
All deps for getting this landed on production have been fixed. So we are good to get this out now! I will get it deployed to production soon.
