### ISSUE TITLE
Run tests per check-in on mozilla-central and mozilla-aurora

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#668]
We would like to enhance our testing to inbound builds so we can test them on a check-in basis. Functional tests only take about 3 minutes right now and we have 4 machines available. So it should totally not be an issue with a backlog.

**Comment by whimboo** [comment]
I was thinking more about this today and the better next step is to enhance our tests to cover not only nightly builds but each check-in for mozilla-central and mozilla-aurora. That can be done by changing the pulse side only whereby for inbound builds we will have to teak the Jenkins config too.

**Comment by whimboo** [comment]
So for non nightly builds we have three different kinds of builds: opt, debug, and pgo. I think for the beginning we should only cover opt. We can enhance that later if we have enough resources. @mjzffr and @sydvicious what do you think?

**Comment by mjzffr** [comment]
I agree that opt-only for now is fine; that's what's been recommended to be in the past when I was asking the same thing about media tests.

@whimboo When you say we have enough resources now to run functional tests per check-in on mozilla-inbound, are you taking into account the resources needed to run media tests once they come in from pf-jenkins?

**Comment by whimboo** [comment]
The change here would not be for inbound but mozilla-central and mozilla-aurora. Inbound we can check later depending on the load of the nodes. It would require additional work to setup.

**Comment by whimboo** [comment]
When we do that I wonder if we should test the opt binary as created by the checkin and the actually created nightly build given that those are two different builds. Or if we keep testing the tinderbox builds for those branches only. IMO the nightly builds we should only test for localized builds.

@rail what do you think? Should we avoid this duplicated testing or would it be valuable to test en-US twice?

**Comment by rail** [comment]
I think there will be no duplicated tests - opt and nightly builds are different. The nightly build usually starts using the "last green build" and uses different mozconfigs (with enabled PGO, updates, etc).

**Comment by whimboo** [comment]
Thanks for that info. So I will take care of it once our jobs have been updated to use mozharness.

**Comment by whimboo** [comment]
Ok, so when re-checking this issue I think we need another refactoring of the pulse config file. Reason is that we need two distinct settings for each branch. So for check-in based tests we only run the en-US builds, whereby for nightly builds we also run different locales and the extended media tests.

For releases we have to differentiate between the releng branches release-mozilla-release and mozilla-release (same for beta), whereby the latter stands for check-in based testing and the former for release candidate builds.

**Comment by whimboo** [comment]
We no longer want to have per-checkin tests in mozmill-ci. Instead taskcluster will be utilized. See [bug 1237550](https://bugzilla.mozilla.org/show_bug.cgi?id=1237550) for the current progress.

Closing as Wontfix.
