### ISSUE TITLE
Upgrade to treeherder-client 1.8.0 for using Hawk credentials

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#672]
Via [bug 1214618](https://bugzilla.mozilla.org/show_bug.cgi?id=1214618) a new version of treeherder-client has been released. We have to update our version to be able to use the Hawk credentials.

CC'ing @edmorley for info.

**Comment by whimboo** [comment]
When we do this upgrade we should have our new credentials at the same time.

**Comment by edmorley** [comment]
treeherder-client 1.8.0 supports both the old and new auth method, so you could update to the newer client even before switching to the new auth, if it's easier/safer to do it in pieces.

I've had a look at treeherder.py and none of the changes between treeherder-client 1.6.0 and 1.8.0 should affect it. The client now depends on requests-hawk, however you aren't using pip's no-deps or peep, so this should get installed without intervention (I'd recommend pinning all deps, but that's orthogonal to updating the client).

**Comment by edmorley** [comment]
v1.8.0 of the client has also been uploaded to the releng pypi mirror (bug 1214655).

**Comment by whimboo** [comment]
treeherder-client 1.8.0 was getting mirrored but not its dependencies. So I cannot continue right now but will do tomorrow once every package has been mirrored.

**Comment by whimboo** [comment]
PR #673 has been merged. I will push it to staging today and later this week to production.

**Comment by edmorley** [comment]
Great, thank you :-)

**Comment by whimboo** [comment]
I had to backout this patch from production because it causes bustage. Some machines are not able to submit results. Mostly its Linux and OS X but not all the time. We will use staging for investigation tomorrow. For progress please see bug https://bugzilla.mozilla.org/show_bug.cgi?id=1215566. Maybe nothing has to be changed on our side.
