### ISSUE TITLE
get_mozharness has to checkout mozharness to a subdirectory

### ISSUE THREAD

**Issue by sydvicious** [mozilla/mozmill-ci#691]
Right now, if you naîvely copy the workspace to your project, files like 'requirements.txt' will clobber what you have already.

**Comment by whimboo** [comment]
We should wait until [bug 1224566](https://bugzilla.mozilla.org/show_bug.cgi?id=1224566) has been merged to mozilla-central, so we can update the mozharness revision at the same time, and also don't break my current mozharness branch.

**Comment by whimboo** [comment]
PR #693 has been merged.
