### ISSUE TITLE
Update Treeherder groups for firefox ui tests

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#711]
As noted by @sydvicious on PR #710 ([comment](https://github.com/mozilla/mozmill-ci/pull/710#discussion_r46287735)) we may want to use a different group for our update tests. Maybe the name for functional tests might also have to change.

Here some proposals:
* Fxf and Fxu-%channel%
* Fff and Ffu-%channel%

@sydvicious and @mjzffr one of you have a different idea for a group symbol?

**Comment by sydvicious** [comment]
I prefer Fff and Ffu.

**Comment by mjzffr** [comment]
I support Fxf and Fxu more only because it gets rid of the 'fu' that was initially pointed out... but I also think the names can just stay as they are because this isn't actually a problem.

**Comment by whimboo** [comment]
We discussed on IRC and agreed on the following group symbols:

* Firefox UI Functional tests: `Fxfn`
* Firefox UI Update tests: `Fxup`

We have chosen 2 letters for the test type to make them better recognizable.

**Comment by whimboo** [comment]
@camd, so we change our group names from `Ff` to `Fxfn` and `Fu` to `Fxup`. What has to be done on Treeherder to ensure that those new jobs are hidden by default? I assume it's something you might be able to do.

**Comment by sydvicious** [comment]
r+

**Comment by whimboo** [comment]
PR #712 has been merged. I will push everything to staging now.
