### ISSUE TITLE
Invalid job results in case of workspace cannot be deleted

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#720]
In case of the workspace cannot be deleted, the submission.py script picks up the exit code from the previous run. We should avoid that because it results in an invalid result:

> Deleting project workspace... Cannot delete workspace: java.nio.file.AccessDeniedException: c:\jenkins\workspace\mozilla-aurora_functional\build\application\firefox-45\core\browser\features\loop@mozilla.org.xpi
ERROR: Cannot delete workspace: java.nio.file.AccessDeniedException: c:\jenkins\workspace\mozilla-aurora_functional\build\application\firefox-45\core\browser\features\loop@mozilla.org.xpi
Archiving artifacts
[PostBuildScript] - Execution post build scripts.
[mozilla-aurora_functional] $ cmd.exe /C '"python -u submission.py --test-type=functional --build-state=completed --repository=mozilla-aurora --revision=%REVISION% --locale=%LOCALE% treeherder_venv && exit %%ERRORLEVEL%%"'
05:50:31 INFO | Run as: ['submission.py', '--test-type=functional', '--build-state=completed', '--repository=mozilla-aurora', '--revision=945377b5fc69', '--locale=de', 'treeherder_venv']
05:50:31 INFO | Activate environment: treeherder_venv\Scripts\activate_this.py
05:50:31 INFO | Read build exit code: 3 (skipped)

Maybe we should create those status files with the Jenkins BUILD_NUMBER included. That way we can ensure to always open the correct file. A problem here could arise if different job types have identical build numbers. But that risk is way lower than the situation we currently have.

**Comment by whimboo** [comment]
In the above case we would assume a test result of skipped while it should be busted.

**Comment by mjzffr** [comment]
Or would be it easier to delete a status file after it has served its purpose? That way we can't reuse it?

**Comment by whimboo** [comment]
That could be another option but could still cause bustage in case the script fails before it will remove the file. So maybe we combine both proposals.

**Comment by mjzffr** [comment]
The file could be removed at the end of a job (lots of opportunity for script failure) or it can be removed at the beginning of the next job as part of making sure that we start from a clean state (less opportunity for failure because it's done at the very beginning).

**Comment by whimboo** [comment]
Well, we cannot run anything before the clean-up workspace pre build step. But I could indeed check if it is possible as a post build step and that AFTER our submission post build step.

**Comment by whimboo** [comment]
Ok, I can add a post build step for deleting the workspace after the submission step. In that case I have renamed both retval.txt and job.txt to *.json given that those files actually contain JSON data. With that I setup a *.json filter for the delete workspace plugin, so we only remove those two files.

**Comment by whimboo** [comment]
PR #721 has been merged. I will push it to staging right now and follow-up with production later today if no regression is visible.
