### ISSUE TITLE
Bump to treeherder-client 2.0.1 to fix incompatible requests-hawk API changes

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#723]
This is critical and we need this ASAP on staging and production otherwise we are not able to upload any reports to treeherder. As @edmorley told on #treeherder the latest requests-hawk has been uploaded to the internal mirror and it breaks us because we use an older version of treeherder-client.

**Comment by whimboo** [comment]
PR #724 got merged. I will push immediately to staging and production.

**Comment by edmorley** [comment]
Sorry the upload caused breakage. The reason it occurred is that requirements file in this repo only specifies the top level dependencies and not also their sub-dependencies. 

As a longer term fix, I would recommend both specifying all sub-dependency versions, and also using `--no-deps` with the pip install to ensure no other unpinned dependencies can sneak in without realising:
https://pip.pypa.io/en/latest/user_guide/#repeatability

That page also discusses an awesome new pip feature (to be released soon in v8) which is roughly equivalent to erikrose/peep (used by Treeherder and a few other projects), which can protect against bad/malicious packages too :-)

**Comment by whimboo** [comment]
Thanks @edmorley. I filed issue #725 to get this investigated and fixed.
