### ISSUE TITLE
Improve python package dependencies 

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#725]
From @edmorley via issue 723:

> Sorry the upload caused breakage. The reason it occurred is that requirements file in this repo only specifies the top level dependencies and not also their sub-dependencies.

> As a longer term fix, I would recommend both specifying all sub-dependency versions, and also using --no-deps with the pip install to ensure no other unpinned dependencies can sneak in without realising:
https://pip.pypa.io/en/latest/user_guide/#repeatability

> That page also discusses an awesome new pip feature (to be released soon in v8) which is roughly equivalent to erikrose/peep (used by Treeherder and a few other projects), which can protect against bad/malicious packages too :-)

This would help to not leave our jobs broken in case of sub packages are getting incompatible updates.

**Comment by edmorley** [comment]
For the workspace requirements.txt, the full deps list is as follows:
```bash
[~/src/mozmill-test]$ mkvirtualenv mozmill
...

(mozmill)[~/src/mozmill-test]$ wget -q "https://github.com/mozilla/mozmill-ci/raw/master/jenkins-master/jobs/ scripts/workspace/requirements.txt"

(mozmill)[~/src/mozmill-test]$ pip install -r requirements.txt
...
Successfully installed boto-2.38.0 mohawk-0.3.0 mozfile-1.2 mozinfo-0.8 requests-2.9.1 requests-hawk-1.0.0 six-1.10.0 treeherder-client-2.0.1

(mozmill)[~/src/mozmill-test]$ pip freeze | grep -v wheel
boto==2.38.0
mohawk==0.3.0
mozfile==1.2
mozinfo==0.8
requests==2.9.1
requests-hawk==1.0.0
six==1.10.0
treeherder-client==2.0.1
```

**Comment by whimboo** [comment]
PR #727 has been merged. Thanks for helping us @edmorley.
