### ISSUE TITLE
Unit tests fail with: AttributeError: 'NoneType' object has no attribute 'close'

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#731]
Seen today when merging PR #730 to master:

> Traceback (most recent call last):
  File "test/configuration/save_config.py", line 59, in <module>
    main()
  File "test/configuration/save_config.py", line 49, in main
    driver.quit()
  File "/mozilla/code/mozmill-ci/test/venv/local/lib/python2.7/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 74, in quit
    self.service.stop()
  File "/mozilla/code/mozmill-ci/test/venv/local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 124, in stop
    self.process.stdout.close()
AttributeError: 'NoneType' object has no attribute 'close'

To reproduce you have to delete the virtualenv for the tests. Looks like a new package version has been uploaded which caused incompatibilities.

**Comment by whimboo** [comment]
This is actually regression between the python package versions selenium 2.48.0 and 2.49.0.

**Comment by davehunt** [comment]
It was raised in https://github.com/SeleniumHQ/selenium/issues/1469 and fixed in https://github.com/SeleniumHQ/selenium/commit/cc07382c786b6b35274957652a7a357d0453279a. We could request a point release.

**Comment by whimboo** [comment]
Ah, thanks Dave! Good to see that it already got fixed. In our case we do not need the latest release, so I can pin to 2.48.0 and wait with an upgrade once this bug got fixed in another release.

**Comment by whimboo** [comment]
I fixed the above via the bustage fix landing on PR #734.

**Comment by whimboo** [comment]
I cherry-picked the PR from this issue for the production branch: https://github.com/mozilla/mozmill-ci/commit/75b9460c80e3fff7ab08bd29ff0aed528f47317f
