### ISSUE TITLE
Update ondemand_update for Treeherder job names and JSON data files

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#767]
This issue is a follow-up for issue #765.

On Treeherder we currently show the updates as `locale-1` because we do not have a build_number in such a case. It would be better to use the source version instead: `ru-42.0`.

Also there are JSON files with build information available or candidate builds on archive.mozilla.org:
http://ftp.mozilla.org/pub/firefox/candidates/46.0b1-candidates/build8/win32/en-US/firefox-46.0b1.json

We can use that to determine the revision and buildid.

**Comment by whimboo** [comment]
Here an example of how it would look like with the source build version as update number. I think that helps a lot!

https://treeherder.allizom.org/#/jobs?repo=mozilla-beta&revision=fb3494d06dfb&filter-tier=1&filter-tier=2&filter-tier=3&filter-searchStr=fx%20ui%20linux%2064%2045

CC @kairo-at and @FlorinMezei.

**Comment by sydvicious** [comment]
@whimboo r+

**Comment by whimboo** [comment]
So PR #782 has been merged and will be live on production tomorrow.

@kairo-at and  @florinmezei please update your ondemand config templates because you no longer need the target build revision for Marionette based ondemand tests! The target version is enough.

**Comment by whimboo** [comment]
Results look great. So I can push to production. Here an example ondemand testrun:
https://treeherder.allizom.org/#/jobs?repo=mozilla-release&revision=e0e51efe7b15&filter-tier=1&filter-tier=2&filter-tier=3&filter-searchStr=localtest&selectedJob=128397

**Comment by whimboo** [comment]
Live on production now.
