### ISSUE TITLE
Retry posting test results to Treeherder

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#804]
We should not only try once to send the results for running or successful. There are cases when Treeherder may be down for some moments and this would cause the whole job to fail. Instead we should use the redo module and try to report multiple times until the submission was successful.

> Traceback (most recent call last):
  File "submission.py", line 347, in <module>
    job = th.create_job(**kwargs)
  File "submission.py", line 103, in create_job
    job.add_revision_hash(self.retrieve_revision_hash())
  File "submission.py", line 144, in retrieve_revision_hash
    response = requests.get(lookup_url, headers=headers)
  File "c:\jenkins\workspace\mozilla-aurora_functional\treeherder_venv\Lib\site-packages\requests\api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "c:\jenkins\workspace\mozilla-aurora_functional\treeherder_venv\Lib\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\jenkins\workspace\mozilla-aurora_functional\treeherder_venv\Lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\jenkins\workspace\mozilla-aurora_functional\treeherder_venv\Lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "c:\jenkins\workspace\mozilla-aurora_functional\treeherder_venv\Lib\site-packages\requests\adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
Build step 'Invoke XShell command' marked build as failure

**Comment by whimboo** [comment]
PR #804 got merged. I will push to staging and later this week to production.

**Comment by whimboo** [comment]
I had to backout the patch from master and staging because it causes bustage:

> Traceback (most recent call last):
  File "submission.py", line 18, in <module>
    from redo import retriable
ImportError: No module named redo

Not sure why that happens because we should have sourced into the venv by that time.

**Comment by whimboo** [comment]
The reason why I haven't seen it locally was that I run the job on the master machine. Here we start Jenkins by sourcing in jenkins-env which also includes the redo package. CCing @mjzffr for info.

**Comment by whimboo** [comment]
We are sourcing into the environment inside of the main method. That way we cannot import redo globally on slave nodes. So I might not be able to use the nifty decorator.

Otherwise we could get rid of the venv-path argument of submission.py and hard-code in it. It would always be the same so the argument seems to be superfluous. @mjzffr what do you think?

**Comment by whimboo** [comment]
https://github.com/mozilla/mozmill-ci/blob/master/jenkins-master/jobs/scripts/workspace/submission.py#L300

**Comment by mjzffr** [comment]
Forgive me, I'm not familiar with the details: if you hardcode the venv-path, you can source into the environment outside of the `__main__` block and therefore use redo on slave nodes?

I have no objections or hard-coding the path.

**Comment by whimboo** [comment]
That's correct. We can source into the venv at the very beginning of the file and import custom modules right after. So I'm going to do that now. Thanks.

**Comment by whimboo** [comment]
PR got landed. I will push to staging immediately and do production later this week if all goes well this time.
