### ISSUE TITLE
Make use of treeherder-client 3.0.0's connection pooling

### ISSUE THREAD

**Issue by edmorley** [mozilla/mozmill-ci#806]
treeherder-client 3.0.0 now re-uses a requests session for the duration of that TreeherderClient instance.

If mozmill-ci updated to 3.0.0 and refactored slightly, so that it re-used the same TreeherderClient for each client usage, you'd get a perf improvement from the HTTP keep-alives.

In addition, we're now recommending people that already have Hawk credentials set them for client GETs and not just submissions (since in the future we may do things like add rate limiting for unauthenticated GETs), so re-using the same client (with credentials set) would help with that too.

See here for more details:
https://bugzilla.mozilla.org/show_bug.cgi?id=1286240

**Comment by whimboo** [comment]
I refactored our treeherder-client code lately via https://github.com/mozilla/mozmill-ci/commit/e83ba75a11a031b565d1d4d88f78c98a048edcff to make use of a single client instance. With that we make use of the credentials all the time.

Upgrading to 3.0.0 sounds like a nice improvement too.

**Comment by whimboo** [comment]
PR #842 just got landed.
