### ISSUE TITLE
Update TC worker type to 'desktop-test-large'

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#812]
As discussed on [bug 1281241](https://bugzilla.mozilla.org/show_bug.cgi?id=1281241#c45) we want to get rid of the specific qa-3-linux-fx-tests workers. Instead our tests as triggered via mozmill-ci should also use 'desktop-test-large' as worker type.

So far as I can see we have to make the following changes:
* Update the client to allow us to use the 'desktop-test-large' worker type
* Change our [functional and update templates](https://github.com/mozilla/mozmill-ci/tree/master/lib/tasks) for the new worker type

@djmitche could you please check the first bullet point, and adjust what's necessary? Thanks.

**Comment by djmitche** [comment]
done

**Comment by whimboo** [comment]
Thanks Dustin! A PR will be up soon.

**Comment by whimboo** [comment]
PR #813 got merged. I pushed this change to our staging instance. If tests today will work fine, I will deploy to production later.

**Comment by whimboo** [comment]
Ok, this is alive on production too. @djmitche you can go ahead and remove the qa- workers. Thanks.

**Comment by djmitche** [comment]
done

**Comment by whimboo** [comment]
Thanks @djmitche! I will call this issue done now!
