### ISSUE TITLE
Bug 1294234 broke our Linux64 tests for Taskcluster

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#815]
The changes on bug 1294234 broke our job submission to Taskcluster for Linux64. The move away from ´test.sh´ as command to ´run-task´ caused bustage. I wonder if we should stop running tests via taskcluster for now, and wait until we can implement our jobs natively once the Nightly graph is active. I don't want to update mozmill-ci again and again.

@mjzffr do you have any concerns?

**Comment by mjzffr** [comment]
Sounds fine. There's a lot of change in TaskCluster now.

**Comment by whimboo** [comment]
This is now live on staging and production.
