### ISSUE TITLE
Remove any calls of add_revision_hash()

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#839]
As I read on [bug 1257602](https://bugzilla.mozilla.org/show_bug.cgi?id=1257602) we should remove all calls to `add_revision_hash()`. The only place where we are submitting results are here:

https://github.com/mozilla/mozmill-ci/blob/6a4372c0e78ab491a466d2c5284b67b6f1a59e90/jenkins-master/jobs/scripts/workspace/submission.py#L120

What does it mean to `get_resultsets()`? Can we get rid of this too in all those places and query the revision directly?

https://github.com/mozilla/mozmill-ci/search?l=Python&q=get_resultsets&utf8=%E2%9C%93

@edmorley I would appreciate some feedback so that I can make the necessary changes.

**Comment by wlach** [comment]
If you're running tests against a repository which is already having revisions stored in treeherder, you should be able to  just add the full 40 character revision as a piece of job metadata. Here's an example from servo-perf:

https://github.com/shinglyu/servo-perf/blob/master/submit_to_perfherder.py#L115

I would also guess you can just kill the calls to get_resultsets as well.

**Comment by whimboo** [comment]
We are still running tests for esr45. I assume that this is the only repository which cannot handle the 40 char revision yet?

**Comment by wlach** [comment]
Any repository can handle the 40 character revision.

**Comment by whimboo** [comment]
A great. So lets see that we can get this fixed!

**Comment by whimboo** [comment]
@wlach what is the alternative in using `get_resultsets()` nowaday? I cannot really find something in the treeherder client 3.0.0.

**Comment by wlach** [comment]
`get_resultsets()` is still there. However, you shouldn't need it anymore (I don't think). Just submit the textual revision with your job data and you should be good to go.

**Comment by whimboo** [comment]
The cases I'm referring to here are more about retrieving data from Treeherder:
https://github.com/mozilla/mozmill-ci/search?l=Python&q=get_resultsets&utf8=%E2%9C%93

Like a list of build jobs for a branch up to a specific revision.

**Comment by wlach** [comment]
Ok, that seems reasonable. get_resultsets should still work for that, let me know if it doesn't.

**Comment by whimboo** [comment]
It works fine, and means I have a PR to upload now. Thanks for your assistance!

**Comment by whimboo** [comment]
PR #842 landed on master. I will push it to staging soon once the fix for issue #843 has been landed too.

**Comment by whimboo** [comment]
I have to reopen because I missed to update a line for the actual submission code which results in:

```
File "submission.py", line 166, in submit
  urljoin('{0}://{1}'.format(self.client.protocol, self.client.host),
AttributeError: 'TreeherderClient' object has no attribute 'protocol'
```

I will have a bustage fix available in a minute.

**Comment by whimboo** [comment]
PR #845 got merged. I will land on staging in a moment.
