### ISSUE TITLE
Add another locale for jobs running on mozilla-central

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#849]
Due to the removal of the aurora branch all the l10n work will happen on mozilla-central now. As such we should add at least one other locale to our matrix to ensure that localized builds at least work.

Given that any landed broken changes for Marionette and Firefox could cause bustage of update tests for the next or overnext nightly I'm not so inclined to add more locales. It would only result in a massive amount of to star failures on Treeherder.

@pike or @flodolo, which other locale should we pick? What makes most sense? Maybe a RTL or Chinese one?

**Comment by whimboo** [comment]
Hm, for Linux we are basically blocked on issue #835.

**Comment by flodolo** [comment]
Asking a dumb question: why do we need to change the list of locales? All aurora locales are now available in central.

**Comment by whimboo** [comment]
As I said above, I don't want to have to star dozen of failures per platform on Treeherder if we have accidentally introduced a regression in Marionette. If one of you wants to do it then I'm fine with it. But my limit would really be 3 locales at maximum. 

Maybe we can skip en-US for functional tests, because we have test coverage on a per commit basis. Which means we could have 3 different locales.

**Comment by flodolo** [comment]
What were the locales tested on aurora, if we had any?

**Comment by whimboo** [comment]
Please have a look at the Treeherder results:

https://treeherder.mozilla.org/#/jobs?repo=mozilla-aurora&revision=105e456d811b8c4616de688e9afdcf0af620b80b&filter-searchStr=fxfn&filter-tier=3

**Comment by flodolo** [comment]
Based on that link, on Aurora we tested: de, en-US, ru, zh-TW. Returning to my initial question: can't we just keep using this list? Or are you asking about extending it?

Hebrew might be a good choice these days for RTL

**Comment by whimboo** [comment]
Given that we run out of resources at the moment I cannot work on getting more locales added beside en-US. If this is something you want to see added please file a PI request. Once implemented it would include that you sheriff the test results on your own.

For now I will close this issue but will reopen in the case you requested it.
